# Generated by Django 5.2.8 on 2026-05-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.CharField(default='reservas/images/sport_football_card.png', max_length=200),
        ),
        migrations.AddField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(default='Cancha Deportiva', max_length=100),
        ),
    ]
